
// This file has been generated by the GUI designer. Do not modify.
namespace Ludo
{
	public partial class MainWindow
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Label lblColor;
		private global::Gtk.Label lblPeð1;
		private global::Gtk.Label lblPeð2;
		private global::Gtk.Label lblPeð3;
		private global::Gtk.Label lblPeð4;
		private global::Gtk.VSeparator vseparator4;
		private global::Gtk.VBox vbox6;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label lblRauður;
		private global::Gtk.Label lblRauðurStat1;
		private global::Gtk.Label lblRauðurStat2;
		private global::Gtk.Label lblRauðurStat3;
		private global::Gtk.Label lblRauðurStat4;
		private global::Gtk.VBox vbox7;
		private global::Gtk.Label lblBlar;
		private global::Gtk.Label lblBlarStat1;
		private global::Gtk.Label lblBlarStat2;
		private global::Gtk.Label lblBlarStat3;
		private global::Gtk.Label lblBlarStat4;
		private global::Gtk.VBox vbox8;
		private global::Gtk.Label lblGulur;
		private global::Gtk.Label lblGulurStat1;
		private global::Gtk.Label lblGulurStat2;
		private global::Gtk.Label lblGulurStat3;
		private global::Gtk.Label lblGulurStat4;
		private global::Gtk.VBox vbox9;
		private global::Gtk.Label lblGrænn;
		private global::Gtk.Label lblGrænnStat1;
		private global::Gtk.Label lblGrænnStat2;
		private global::Gtk.Label lblGrænnStat3;
		private global::Gtk.Label lblGrænnStat4;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.Label lblText;
		private global::Gtk.Label lblFinal;
		private global::Gtk.Button button1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Ludo.MainWindow
			this.Name = "Ludo.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Ludo");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.BorderWidth = ((uint)(1));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child Ludo.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.lblColor = new global::Gtk.Label ();
			this.lblColor.Name = "lblColor";
			this.lblColor.LabelProp = global::Mono.Unix.Catalog.GetString ("Litur");
			this.vbox5.Add (this.lblColor);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.lblColor]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.lblPeð1 = new global::Gtk.Label ();
			this.lblPeð1.Name = "lblPeð1";
			this.lblPeð1.LabelProp = global::Mono.Unix.Catalog.GetString ("Peð 1 :");
			this.vbox5.Add (this.lblPeð1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.lblPeð1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.lblPeð2 = new global::Gtk.Label ();
			this.lblPeð2.Name = "lblPeð2";
			this.lblPeð2.LabelProp = global::Mono.Unix.Catalog.GetString ("Peð 2 :");
			this.vbox5.Add (this.lblPeð2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.lblPeð2]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.lblPeð3 = new global::Gtk.Label ();
			this.lblPeð3.Name = "lblPeð3";
			this.lblPeð3.LabelProp = global::Mono.Unix.Catalog.GetString ("Peð 3 :");
			this.vbox5.Add (this.lblPeð3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.lblPeð3]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.lblPeð4 = new global::Gtk.Label ();
			this.lblPeð4.Name = "lblPeð4";
			this.lblPeð4.LabelProp = global::Mono.Unix.Catalog.GetString ("Peð 4 :");
			this.vbox5.Add (this.lblPeð4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.lblPeð4]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			this.hbox1.Add (this.vbox5);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox5]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vseparator4 = new global::Gtk.VSeparator ();
			this.vseparator4.Name = "vseparator4";
			this.hbox1.Add (this.vseparator4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vseparator4]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lblRauður = new global::Gtk.Label ();
			this.lblRauður.Name = "lblRauður";
			this.lblRauður.Xpad = 30;
			this.lblRauður.Ypad = 2;
			this.lblRauður.LabelProp = global::Mono.Unix.Catalog.GetString ("Rauður");
			this.hbox2.Add (this.lblRauður);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.lblRauður]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox6.Add (this.hbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox2]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.lblRauðurStat1 = new global::Gtk.Label ();
			this.lblRauðurStat1.Name = "lblRauðurStat1";
			this.lblRauðurStat1.LabelProp = global::Mono.Unix.Catalog.GetString ("Byrjun");
			this.vbox6.Add (this.lblRauðurStat1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.lblRauðurStat1]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.lblRauðurStat2 = new global::Gtk.Label ();
			this.lblRauðurStat2.Name = "lblRauðurStat2";
			this.lblRauðurStat2.LabelProp = global::Mono.Unix.Catalog.GetString ("Byrjun");
			this.vbox6.Add (this.lblRauðurStat2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.lblRauðurStat2]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.lblRauðurStat3 = new global::Gtk.Label ();
			this.lblRauðurStat3.Name = "lblRauðurStat3";
			this.lblRauðurStat3.LabelProp = global::Mono.Unix.Catalog.GetString ("Byrjun");
			this.vbox6.Add (this.lblRauðurStat3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.lblRauðurStat3]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.lblRauðurStat4 = new global::Gtk.Label ();
			this.lblRauðurStat4.Name = "lblRauðurStat4";
			this.lblRauðurStat4.LabelProp = global::Mono.Unix.Catalog.GetString ("Byrjun");
			this.vbox6.Add (this.lblRauðurStat4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.lblRauðurStat4]));
			w13.Position = 4;
			w13.Expand = false;
			w13.Fill = false;
			this.hbox1.Add (this.vbox6);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox6]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.lblBlar = new global::Gtk.Label ();
			this.lblBlar.Name = "lblBlar";
			this.lblBlar.Xpad = 30;
			this.lblBlar.Ypad = 2;
			this.lblBlar.LabelProp = global::Mono.Unix.Catalog.GetString ("Blar");
			this.vbox7.Add (this.lblBlar);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.lblBlar]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.lblBlarStat1 = new global::Gtk.Label ();
			this.lblBlarStat1.Name = "lblBlarStat1";
			this.lblBlarStat1.LabelProp = global::Mono.Unix.Catalog.GetString ("Byrjun");
			this.vbox7.Add (this.lblBlarStat1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.lblBlarStat1]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.lblBlarStat2 = new global::Gtk.Label ();
			this.lblBlarStat2.Name = "lblBlarStat2";
			this.lblBlarStat2.LabelProp = global::Mono.Unix.Catalog.GetString ("Byrjun");
			this.vbox7.Add (this.lblBlarStat2);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.lblBlarStat2]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.lblBlarStat3 = new global::Gtk.Label ();
			this.lblBlarStat3.Name = "lblBlarStat3";
			this.lblBlarStat3.LabelProp = global::Mono.Unix.Catalog.GetString ("Byrjun");
			this.vbox7.Add (this.lblBlarStat3);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.lblBlarStat3]));
			w18.Position = 3;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.lblBlarStat4 = new global::Gtk.Label ();
			this.lblBlarStat4.Name = "lblBlarStat4";
			this.lblBlarStat4.LabelProp = global::Mono.Unix.Catalog.GetString ("Byrjun");
			this.vbox7.Add (this.lblBlarStat4);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.lblBlarStat4]));
			w19.Position = 4;
			w19.Expand = false;
			w19.Fill = false;
			this.hbox1.Add (this.vbox7);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox7]));
			w20.Position = 3;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.lblGulur = new global::Gtk.Label ();
			this.lblGulur.Name = "lblGulur";
			this.lblGulur.Xpad = 30;
			this.lblGulur.Ypad = 2;
			this.lblGulur.LabelProp = global::Mono.Unix.Catalog.GetString ("Gulur");
			this.vbox8.Add (this.lblGulur);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.lblGulur]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.lblGulurStat1 = new global::Gtk.Label ();
			this.lblGulurStat1.Name = "lblGulurStat1";
			this.lblGulurStat1.LabelProp = global::Mono.Unix.Catalog.GetString ("Byrjun");
			this.vbox8.Add (this.lblGulurStat1);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.lblGulurStat1]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.lblGulurStat2 = new global::Gtk.Label ();
			this.lblGulurStat2.Name = "lblGulurStat2";
			this.lblGulurStat2.LabelProp = global::Mono.Unix.Catalog.GetString ("Byrjun");
			this.vbox8.Add (this.lblGulurStat2);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.lblGulurStat2]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.lblGulurStat3 = new global::Gtk.Label ();
			this.lblGulurStat3.Name = "lblGulurStat3";
			this.lblGulurStat3.LabelProp = global::Mono.Unix.Catalog.GetString ("Byrjun");
			this.vbox8.Add (this.lblGulurStat3);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.lblGulurStat3]));
			w24.Position = 3;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.lblGulurStat4 = new global::Gtk.Label ();
			this.lblGulurStat4.Name = "lblGulurStat4";
			this.lblGulurStat4.LabelProp = global::Mono.Unix.Catalog.GetString ("Byrjun");
			this.vbox8.Add (this.lblGulurStat4);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.lblGulurStat4]));
			w25.Position = 4;
			w25.Expand = false;
			w25.Fill = false;
			this.hbox1.Add (this.vbox8);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox8]));
			w26.Position = 4;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.lblGrænn = new global::Gtk.Label ();
			this.lblGrænn.Name = "lblGrænn";
			this.lblGrænn.Xpad = 30;
			this.lblGrænn.Ypad = 2;
			this.lblGrænn.Xalign = 0F;
			this.lblGrænn.LabelProp = global::Mono.Unix.Catalog.GetString ("Grænn");
			this.vbox9.Add (this.lblGrænn);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.lblGrænn]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.lblGrænnStat1 = new global::Gtk.Label ();
			this.lblGrænnStat1.Name = "lblGrænnStat1";
			this.lblGrænnStat1.LabelProp = global::Mono.Unix.Catalog.GetString ("Byrjun");
			this.vbox9.Add (this.lblGrænnStat1);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.lblGrænnStat1]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.lblGrænnStat2 = new global::Gtk.Label ();
			this.lblGrænnStat2.Name = "lblGrænnStat2";
			this.lblGrænnStat2.LabelProp = global::Mono.Unix.Catalog.GetString ("Byrjun");
			this.vbox9.Add (this.lblGrænnStat2);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.lblGrænnStat2]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.lblGrænnStat3 = new global::Gtk.Label ();
			this.lblGrænnStat3.Name = "lblGrænnStat3";
			this.lblGrænnStat3.LabelProp = global::Mono.Unix.Catalog.GetString ("Byrjun");
			this.vbox9.Add (this.lblGrænnStat3);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.lblGrænnStat3]));
			w30.Position = 3;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.lblGrænnStat4 = new global::Gtk.Label ();
			this.lblGrænnStat4.Name = "lblGrænnStat4";
			this.lblGrænnStat4.LabelProp = global::Mono.Unix.Catalog.GetString ("Byrjun");
			this.vbox9.Add (this.lblGrænnStat4);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.lblGrænnStat4]));
			w31.Position = 4;
			w31.Expand = false;
			w31.Fill = false;
			this.hbox1.Add (this.vbox9);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox9]));
			w32.PackType = ((global::Gtk.PackType)(1));
			w32.Position = 5;
			w32.Expand = false;
			w32.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox2.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator1]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblText = new global::Gtk.Label ();
			this.lblText.Name = "lblText";
			this.lblText.LabelProp = global::Mono.Unix.Catalog.GetString ("Þu fekkst :");
			this.vbox2.Add (this.lblText);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblText]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			this.vbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.lblFinal = new global::Gtk.Label ();
			this.lblFinal.Name = "lblFinal";
			this.vbox1.Add (this.lblFinal);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.lblFinal]));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("Kasta tening");
			this.vbox1.Add (this.button1);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.button1]));
			w38.Position = 2;
			w38.Expand = false;
			w38.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 614;
			this.DefaultHeight = 232;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
		}
	}
}
